### PR TITLE
Added solution 100% faster on leetcode

### PR DESCRIPTION
**Pull request by mohammedarbaz119**

### CODE REVIEW

**Comment by asdsyd** [comment]
I understand your solution is 100% faster but I wanted this particular solution to work. Can you help in pointing out the errors that in my solution .

**Comment by mohammedarbaz119** [comment]
ok wait lemme check

**Comment by asdsyd** [comment]
For your reference:
https://youtu.be/W9QJ8HaRvJQ?t=5342 
timestamp included. Thanks

**Comment by mohammedarbaz119** [comment]
what sort of error did you get in leetcode?  TLE?

**Comment by asdsyd** [comment]
Many errors that I cannot list. Basically has to do with the methods i g.

**Comment by mohammedarbaz119** [comment]
bro  but you sent the infinite array one i have to work on first and last right?

**Comment by mohammedarbaz119** [comment]
ok i'll try to make it fix

**Comment by mohammedarbaz119** [comment]
it seems like you have many undeclared variables

**Comment by mohammedarbaz119** [comment]
bro im done now how should i do it 
sorry i forgot how to do this

**Comment by asdsyd** [comment]
? What do you mean?

**Comment by mohammedarbaz119** [comment]
check the code

**Review by asdsyd — CHANGES_REQUESTED** [review]
You missed out binary search code

**Comment by mohammedarbaz119** [comment]
i fixed it 
u added unneccessary binary seach in mian function and many more mistakes

**Comment by mohammedarbaz119** [comment]
so how's the code now

**Comment by asdsyd** [comment]
It's not running on leetcode

**Comment by mohammedarbaz119** [comment]
dont put psvm

**Comment by asdsyd** [comment]
This is working. Thanks for contributing. 🚀

**Review by asdsyd — APPROVED** [review]
Works well.

**Comment by mohammedarbaz119** [comment]
if you want to remove psvm you can

**Comment by asdsyd** [comment]
'Closes #7 '

**Comment by mohammedarbaz119** [comment]
lemme Know if you have any problems :)

**Pull request merged**
